global:
  scrape_interval: 5s  # Adjust as needed
rule_files:
  - "alert_rules.yml"
 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      #- targets: ["192.168.50.25:9090"]
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]  # If you have node exporter running
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] 